export default {
    hablar: [
        "español",
        "inglés",
        "portugués",
        "francés",
        "italiano",
        "catalán",
        "vasco",
        "alemán",
        "holandés",
        "ruso",
        "griego",
        "chino",
        "japonés",
        "tagalo",
        "coreano",
        "vietnamita",
        "camboyano",
        "indonesio",
        "hindi",
        "árabe",
        "creol haitiano",
        "mapudungún",
        "quechua",
        "aymara",
        "guaraní",
        "maya",
        "rapanui"
    ],
    comer: [
        "mucho pan",
        "mucho arroz",
        "muchos tallarines",
        "mucho puré",
        "mucha carne",
        "mucho pollo",
        "mucho pezcado",
        "mucho chancho",
        "mucho jamón",
        "mucho quezo",
        "mucho huevo"
    ],
    vivir: [
        "en Antofagasta",
        "en Viña del Mar",
        "en Valparaíso",
        "en Santiago",
        "en Temuco",
        "en Punta Arenas",
        "en la Isla de Pascua"
    ]
}
